# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-12-03T05:54:47Z"
  labels:
    app: house-calendar
  name: db
spec:
  containers:
  - args:
    - postgres
    image: docker.io/library/postgres:latest
    name: postgres
    ports:
    - containerPort: 5432
      hostPort: 5432
    resources: {}
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_DB
      value: hc_events
    livenessProbe:
      exec:
        command:
        - pg_isreaady -U postgres
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: 20a750b76538836adbcbcba1c1b7fd5a8220d60b41b8410ce4861e592b29de9c-pvc
  restartPolicy: Never
  volumes:
  - name: 20a750b76538836adbcbcba1c1b7fd5a8220d60b41b8410ce4861e592b29de9c-pvc
    persistentVolumeClaim:
      claimName: 20a750b76538836adbcbcba1c1b7fd5a8220d60b41b8410ce4861e592b29de9c
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: phppgadmin
  labels:
    name: phppgadmin
    app: house-calendar
spec:
  containers:
  - name: phppgadmin
    image: bitnami/phppgadmin
    resources: {}
    ports:
      - containerPort: 8080
        hostPort: 8080
      - containerPort: 8443
        hostPort: 8443
---
apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: house-calendar
    name: api
spec:
  initContainers:
  - name: init-alembic
    image: ghcr.io/howaboutudance/hematite/house-calendar-init
    env:
    - name: POSTGRES_MIGRATE_URI
      value: postgresql+psycopg2://postgres:postgres@db.dns.podman:5432/hc_events
  containers:
  - image: ghcr.io/howaboutudance/hematite/house-calendar-api:latest
    name: api
    ports:
    - containerPort: 8000
      hostPort: 8000
    resources: {}
    env:
      - name: POSTGRES_URI
        value: postgresql+asyncpg://postgres:postgres@db.dns.podman:5432/hc_events
      - name: HOST_SERVER
        value: 0.0.0.0
      - name: HOST_PORT
        value: 8000