version: '3.8'

services:
  api:
    build: ./
    ports:
      - 8000:8000
    environment:
      - POSTGRES_URI=postgresql+asyncpg://postgres:postgres@db:5432/hc_events
      - HOST_SERVER=0.0.0.0
      - HOST_PORT=8000
    depends_on:
      - db
  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hc_events
  