[default]
test_var="test_var"
postgres_server_ip="127.0.0.1:5432"
postgres_server_db="hc_events"
postgres_base_uri = "@format {this.postgres_server_credentials}@{this.postgres_server_ip}/{this.postgres_server_db}" 
alembic_uri = "@format postgresql+psycopg2://{this.postgres_base_uri}"
postgres_uri = "@format postgresql+asyncpg://{this.postgres_base_uri}"
origins = []
host_server="0.0.0.0"
host_port=8000

[testing]
origins = ["http://localhost", "http://localhost:3000"]

[ci]
origins = ["http://localhost", "http://localhost:3000"]
postgres_server_ip = "alembic-postgres.dns.podman:5432"