[default]
test_var="test_var"
postgres_uri = ""
origins = []
host_server="0.0.0.0"
host_port=8000

[testing]
postgres_uri = "postgresql+asyncpg://postgres:postgres@127.0.0.1:5432/hc_events"
origins = ["http://localhost", "http://localhost:3000"]

[ci]
postgres_uri = "postgresql+asyncpg://postgres:postgres@127.0.0.1:5432/hc_events"
origins = ["http://localhost", "http://localhost:3000"]